name: Build For Mac 

on:
  push: 
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install SCons (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y scons

      - name: Install SCons (macOS)
        if: runner.os == 'macOS'
        run: brew install scons

      - name: Install SCons (Windows)
        if: runner.os == 'Windows'
        run: choco install -y scons

      - name: Run SCons build
        run: scons

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: |
            build/
            *.exe
            *.out
            *.app
    
